[package]
name = "solana_rpc"
version = "0.1.0"
description = "Interact with Solana blockchain from the Internet Computer."
authors = ["mFactory team"]
edition = "2021"

[profile.release]
debug = false
lto = true
strip = true
opt-level = 's'

# Required by `ic-test-utilities-load-wasm`
[profile.canister-release]
inherits = "release"

[dependencies]
anyhow = "1.0.86"
base64 = "0.22.1"
bs58 = "0.5.1"
candid = { workspace = true }
getrandom = { version = "0.2", features = ["custom"] }
ic-canister-log = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-timers = { version = "0.8.0" }
ic-crypto-ed25519 = { workspace = true }
ic-canisters-http-types = { workspace = true }
ic-management-canister-types = { workspace = true }
#ic-stable-structures = "0.6"
ic-types = { workspace = true }
hex = "0.4.3"
lazy_static = "1.4.*"
serde = "1"
serde-big-array = "0.5.1"
serde_json = "^1.0.117"
serde_bytes = "^0.11.14"
zeroize = "1.8.1"
url = "2.5.0"
thiserror = "^1.0.61"
semver = "1.0.23"
num-traits = "0.2.17"
bincode = "1.3.3"

#[dev-dependencies]
#ic-ic00-types = { git = "https://github.com/dfinity/ic", rev = "release-2023-09-27_23-01" }
#ic-base-types = { git = "https://github.com/dfinity/ic", rev = "release-2023-09-27_23-01" }
#ic-config = { git = "https://github.com/dfinity/ic", rev = "release-2023-09-27_23-01" }
#ic-state-machine-tests = { git = "https://github.com/dfinity/ic", rev = "release-2023-09-27_23-01" }
#ic-test-utilities-load-wasm = { git = "https://github.com/dfinity/ic", rev = "release-2023-09-27_23-01" }
#assert_matches = "1.5"

[workspace.dependencies]
candid = { version = "0.10" }
ic-crypto-ed25519 = { git = "https://github.com/dfinity/ic", package = "ic-crypto-ed25519" }
ic-canisters-http-types = { git = "https://github.com/dfinity/ic", package = "ic-canisters-http-types" }
ic-management-canister-types = { git = "https://github.com/dfinity/ic", package = "ic-management-canister-types" }
ic-canister-log = "0.2"
ic-cdk = "0.14"
ic-types = "0.7"

#[patch.crates-io]
#wasm-bindgen = { git = "https://github.com/dfinity/wasm-bindgen", rev = "9cde9c9a88c1fad13a8663277650e01b5671843e" }
#
#[workspace]
#members = ["e2e/rust"]
