comment_width = 100
max_width = 120
edition = "2021"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
format_code_in_doc_comments = true
format_strings = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
