#!/usr/bin/env bash

PACKAGE=ic-solana-provider
WASM_FILE=target/wasm32-unknown-unknown/release/ic_solana_provider.wasm
DID_PATH=./src/$PACKAGE/$PACKAGE.did

# Build the canister
cargo build -j1 --release --target wasm32-unknown-unknown --package $PACKAGE

# Extract the did file
candid-extractor $WASM_FILE > $DID_PATH

# optimize wasm file
# ic-wasm $WASM_FILE -o $WASM_FILE metadata candid:service -f $DID_PATH -v public

gzip --no-name --force $WASM_FILE
cp $WASM_FILE.gz ./src/$PACKAGE/$PACKAGE.wasm.gz

# Deploy schnorr canister
dfx deploy schnorr_canister

# Get the canister id
schnorr_canister_id=$(dfx canister id schnorr_canister)

# Deploy the solana canister and set the schnorr canister id
dfx deploy ic-solana-provider --argument "( record { nodesInSubnet = 28; schnorr_canister = opt \"${schnorr_canister_id}\" } )" --mode=reinstall -y
