#!/usr/bin/env bash

CANISTER=ic-solana-provider
CANISTER_WASM=target/wasm32-unknown-unknown/release/$(echo $CANISTER | tr '-' '_').wasm

# Build the canister
cargo build --release --target wasm32-unknown-unknown --package $CANISTER

# Extract the did file
candid-extractor $CANISTER_WASM > ./src/$CANISTER/$CANISTER.did

# optimize wasm file
# ic-wasm $CANISTER_WASM -o $CANISTER_WASM metadata candid:service -f $DID_PATH -v public

gzip --no-name --force $CANISTER_WASM
cp $CANISTER_WASM.gz ./src/$CANISTER/$CANISTER.wasm.gz

# Deploy the solana canister and set the schnorr canister id
dfx deploy ic-solana-provider --argument "(record {})" --mode=reinstall -y

# Get the canister id
CANISTER_ID=$(dfx canister id ic-solana-provider)

echo "Solana canister id: $CANISTER_ID"

# Deploy the test canister
dfx deploy test_canister --argument "( \"${CANISTER_ID}\" )" --mode=reinstall -y

echo "Test canister id: $CANISTER_ID"

echo "Done"
