#!/usr/bin/env bash

set -eEuo pipefail

SCRIPT_NAME=$(basename "$0")
ARTIFACTS_DIR="./artifacts"
BUILD_MODE=${BUILD_MODE:-"production"}

title() {
  echo -e "IC Solana Reproducible Builds"
}

function usage() {
  cat <<EOF

Usage:
  ${SCRIPT_NAME} [OPTIONS]

Options:
  --rpc         Build the RPC canister
  --wallet      Build the Wallet canister

  -h, --help    Show this help message
EOF
}

function help() {
  cat <<EOF

Helper script to facilitate the building of the canisters in the IC Solana project in a reproducible way.

NOTE: This requires a working Docker installation.
EOF
}

exec_function() {
  local function_name="$1"
  shift
  echo "------------------------------------------------------"
  echo -e "\033[1mSTART:\033[0m $function_name"
  "$function_name" "$@"
  echo -e "\033[1mCOMPLETED:\033[0m $function_name"
}

# Check if Docker is installed
check_docker() {
  if ! command -v docker &>/dev/null; then
    echo "ERROR: Docker is not installed or not in PATH." >&2
    exit 1
  fi

  if ! docker info >/dev/null 2>&1; then
    echo "ERROR: Docker daemon is not running or you don't have permissions." >&2
    exit 1
  fi
}

#############################################
# FEATURES                                  #
#############################################

function build() {
  local project_name=$1
  local target=$2

  echo "Building the '$project_name' canister in '$BUILD_MODE' mode..."

  # Build the canister
  docker build --build-arg BUILD_MODE=$BUILD_MODE -t ic-solana-$project_name --target $target .

  local container_id
  container_id=$(docker create "ic-solana-${project_name}")

  # Ensure the artifacts directory exists
  mkdir -p "${ARTIFACTS_DIR}/${project_name}"

  # Copy artifacts from the container to the host
  docker cp "${container_id}:/code/artifacts/." "${ARTIFACTS_DIR}/${project_name}/"

  # Clean up the container
  docker rm "$container_id"

  # Remove the Docker image to save space
  docker rmi "ic-solana-${project_name}" --force

  echo "Artifacts for '$project_name' have been copied to '${ARTIFACTS_DIR}/${project_name}/'"
}

function build_rpc() {
  build rpc build_rpc
}

function build_wallet() {
  build wallet build_wallet
}

#############################################
# SCRIPT OPTIONS                            #
#############################################

if [[ $# -eq 0 ]]; then
  title
  usage
  exit 0
fi

check_docker

# Parse command-line arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
  -h | --help)
    title
    usage
    help_info
    exit 0
    ;;
  --rpc)
    exec_function build_rpc
    shift
    ;;
  --wallet)
    exec_function build_wallet
    shift
    ;;
  *)
    echo -e "ERROR: Unknown argument '$1'" >&2
    usage
    echo -e "\nUse '${SCRIPT_NAME} --help' for more information." >&2
    exit 1
    ;;
  esac
done
