#!/usr/bin/env bash

# Reinstall all canisters and run E2E tests in your local environment.
#dfx canister create --all &&
dfx deploy ic-solana-provider --mode reinstall -y &&

dfx canister call ic-solana-provider get_address '()'
dfx canister call ic-solana-provider sol_getBalance '("AAAAUrmaZWvna6vHndc5LoVWUBmnj9sjxnvPz5U3qZGY")'
dfx canister call ic-solana-provider sol_getAccountInfo '("AAAAUrmaZWvna6vHndc5LoVWUBmnj9sjxnvPz5U3qZGY")'

echo Done
