#!/usr/bin/env bash

CANISTER_ID=solana_rpc

# Reinstall all canisters and run E2E tests in your local environment.
(
    dfx canister create --all &&
    npm run generate &&
    dfx deploy $CANISTER_ID --mode reinstall -y &&
#    dfx deploy $CANISTER_ID --argument "(record {nodesInSubnet = 28})" --mode reinstall -y &&
#    dfx deploy $CANISTER_ID --argument "(record {nodesInSubnet = 13})" --mode reinstall -y &&
#    dfx deploy $CANISTER_ID --argument "(record {nodesInSubnet = 28})" --mode reinstall -y &&
    dfx canister call $CANISTER_ID request &&
    echo Done
)
