#!/usr/bin/env bash

dfx canister call ic-solana-provider get_address '()'
dfx canister call ic-solana-provider sol_latestBlockhash '()'
dfx canister call ic-solana-provider sol_getBalance '("AAAAUrmaZWvna6vHndc5LoVWUBmnj9sjxnvPz5U3qZGY")'
dfx canister call ic-solana-provider sol_getTokenBalance '("GeDhDhMT8Cw4hi1vJyRtU9wqWBXURchDoZxttBfFKq9r")'
dfx canister call ic-solana-provider sol_getAccountInfo '("GeDhDhMT8Cw4hi1vJyRtU9wqWBXURchDoZxttBfFKq9r")'
dfx canister call ic-solana-provider sol_getTransaction '("1zhKkhptmaKR83DMbn7FuBRZM2mHGgLSFEuAGoocET5wPywH4gy3FktfT8dL3FV4LJct86pBTsTTANv5NvNTAEN")'

#dfx canister call ic-solana-provider sol_sendTransaction '( record { instructuons: } )'
