#!/usr/bin/env bash

echo "Fetching solana address..."
dfx canister call ic-solana-rpc sol_address '()'

echo "Fetching latest blockhash..."
dfx canister call ic-solana-rpc sol_latestBlockhash '("devnet")'

echo "Fetching balance..."
dfx canister call ic-solana-rpc sol_getBalance '("devnet","AAAAUrmaZWvna6vHndc5LoVWUBmnj9sjxnvPz5U3qZGY")'

echo "Fetching token balance..."
dfx canister call ic-solana-rpc sol_getTokenBalance '("devnet","GeDhDhMT8Cw4hi1vJyRtU9wqWBXURchDoZxttBfFKq9r")'

echo "Fetching account info..."
dfx canister call ic-solana-rpc sol_getAccountInfo '("devnet","GeDhDhMT8Cw4hi1vJyRtU9wqWBXURchDoZxttBfFKq9r")'

echo "Fetching transaction..."
dfx canister call ic-solana-rpc sol_getTransaction '("devnet","1zhKkhptmaKR83DMbn7FuBRZM2mHGgLSFEuAGoocET5wPywH4gy3FktfT8dL3FV4LJct86pBTsTTANv5NvNTAEN")'

echo "Fetching signature status..."
dfx canister call ic-solana-rpc sol_getSignatureStatuses '("devnet", ["1zhKkhptmaKR83DMbn7FuBRZM2mHGgLSFEuAGoocET5wPywH4gy3FktfT8dL3FV4LJct86pBTsTTANv5NvNTAEN"])'

echo "Fetching rpc providers..."
dfx canister call ic-solana-rpc getProviders '()'

echo "Fetching metrics..."
dfx canister call ic-solana-rpc getMetrics '()'

#dfx canister call ic-solana-rpc getNodesInSubnet '()'

echo "Done"
